version: '3'
services:
        web:
                image: pyproj_v1
                build: .
                ports:
                        - "8089:8080"

                volumes:
                        - persistent_volume: /app/volumes

