version: '3'
services:
        web:
                image: pyproj_v1
                build: .
                ports:
                        - "4002:4000"

                volumes:
                        - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /vscode/pyproj/volumes
      tty: true
